version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
