version: '3.8'

services:
  app:
    build: .
    env_file:
      - ./.env # sua env
    ports:
      - '8080:8080'
    environment:
      MONGODB_URI: mongodb://mongo:27017/seu_banco_de_dados
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
